version: "3.9"
services:
  db:
    # Change image name to "your_username/mysql"
    image: dahas68/mysql
    # Mandatory for authentication
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: .
      dockerfile: docker/MySQL.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always
    # Connect locally to MySQL in container using localhost:9906 
    ports:
      - "9906:3306"
      
  node:
    # Change image name to "your_username/nodejs"
    image: dahas68/nodeapp
    build:
      context: .
      dockerfile: docker/Node.Dockerfile
    # Launch app in browser using localhost:9090
    ports:
      - "9090:8080"
    # Symlink container to local volume
    volumes:
      - ./:/usr/src/app
    # Create db container first 
    depends_on:
     - db
    # Wait until db is ready to connect
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]

  # php:
  #   # Change image name to "your_username/nodejs"
  #   image: dahas68/phpapp
  #   build:
  #     context: .
  #     dockerfile: docker/PHP.Dockerfile
  #   # Launch app in browser using localhost:9000
  #   ports:
  #     - "9000:80"
  #   # Symlink container to local volume
  #   volumes:
  #     - ./:/var/www/html
  #   # Create db container first 
  #   links:
  #    - db
  #   # Wait until db is ready to connect
  #   # command: ["./wait-for-it.sh", "db:3306", "--", "apachectl", "restart"]
